version: "3.6"

services:
  database:
    image: postgres
    volumes:
      - ./server/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: loomi
    restart: always